language: node_js
node_js:
  - '10'
services:
  - docker
env:
  - DEFAULT_TAG=latest
  - DEFAULT_TAG=develop
script:
  - cp test/.env.test .env
  - docker-compose -f docker-compose.yml -f docker-compose.demo.yml up -d engine camundadb bodgeit juice-shop nginx scanner-infrastructure-nmap scanner-webapplication-arachni scanner-webapplication-zap scanner-infrastructure-amass scanner-webapplication-sslyze scanner-webserver-nikto scanner-infrastructure-ssh
  - cd test
  - npm ci
  - npm test -- --verbose --forceExit
after_failure:
  - docker ps -a
  - docker logs securecodebox_engine_1
  - docker logs securecodebox_scanner-webapplication-zap_1
  - docker logs securecodebox_scanner-webapplication-arachni_1
  - docker logs securecodebox_scanner-infrastructure-amass_1
  - docker logs securecodebox_scanner-infrastructure-nmap_1
  - docker logs securecodebox_scanner-webapplication-sslyze_1
  - docker logs securecodebox_scanner-webserver-nikto_1
