version: '2.1'
services:
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
    networks:
      - frontend
  bodgeit:
    image: securecodebox/bodgeit
    ports:
      - 8081:8080
    networks:
      - frontend
  nginx:
    image: nginx
    ports:
      - 8111:80
    networks:
      - frontend
  old-wordpress:
    image: wordpress/4.7.5-php7.1-fpm
    ports:
      - 8000:80
    networks:
      - frontend